### ISSUE TITLE
Develop UI for Alerts Detail Page

### ISSUE THREAD

**Issue by PatrickBCMolloy** [postlight/carnival-alerts-pipeline#3]
User Story: As a casino staff member I would like to see details about the player so that i can know who I’m approaching, address them by name, and offer a more personalized experience

User Story: As a casino staff member I would like to see the location of an alert so that I can easily navigate to it on the floor

User Story: As a casino manager I would like to see the time elapsed since an alert triggered so that I can know how long the guest has been waiting for action

**Comment by mfickanderson** [comment]
Thes three stories should be split up.

**Comment by PatrickBCMolloy** [comment]
split these up, removing this one

**Comment by PatrickBCMolloy** [comment]
split these up, removing this one
